### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by mrhornung** [Inirit/Reuploader#1]
> Unfortunately, I'm experiencing problems.
> The image gets uploaded all right, and i get a short notification showing the imgur link. If I'm really quick and click on this link before the notification vanishes, imgur opens and i can see that it was actually uploaded.
> something's wrong with the clipboard, though. i get the "paste" option in the context menu, so something is in there, but when i try to paste nothing happens.
> i appreciate the effort, as I too was looking for a replacement for rehost. Will keep this installed in the hope it will get fixed. thanks.

this was my review from mozilla.org.
yes, i have the latest version (1.0.0.3).
update: when i wrote the review yesterday, i tried pasting into a web form, libreoffice write and libreoffice draw. today, i tried pasting into notepad, and when doing so, the paste option was greyed out in the context menu. don't know if this is helpful somehow.
by the way, i tried it on to different computers: one with linux mint 18.2/firefox 56, the other linux mint 17.3/firefox 57.

**Comment by Inirit** [comment]
Are the two Linux computers the only ones you've used, or is the extension not working for you on a Windows computer as well?

I've not tested the extension on Linux, I'll see if I can set up a VM and reproduce the problem.

**Comment by Inirit** [comment]
I created a VM with Linux Mint 18.2 and I believe I've reproduced the problem, will update once I figure out a solution.

**Comment by Inirit** [comment]
I've implemented a fix, update should be published for Firefox soon.

**Comment by Inirit** [comment]
Just submitted 1.0.0.4. Please update to it when convenient and let me know if it fixes your issue.

**Comment by mrhornung** [comment]
yes, it works now. thank you so much!!!

**Comment by Inirit** [comment]
Great, thanks for verifying.
