### ISSUE TITLE
postimages.org?

### ISSUE THREAD

**Issue by gabri25ele** [Inirit/Reuploader#3]
is possible add http://postimages.org/ in the "upload service"?
thanks

**Comment by Inirit** [comment]
I'll look into it.

**Comment by Inirit** [comment]
I've added support for this in version 1.0.0.5. Please update when convenient and let me know if it works as you expect.

**Comment by gabri25ele** [comment]
fabulous, Thank You, very Thank You!
ok, now is quite perfect :)

**Comment by Inirit** [comment]
Great, thanks for verifying.
