### ISSUE TITLE
problem with option "Prevent accessibility services"

### ISSUE THREAD

**Issue by gabri25ele** [Inirit/Reuploader#5]
in Options > ‘Privacy and security’ > ‘Permissions’,  If I check ‘ Prevent accessibility services from accessing your browser’, the extension NOT work anymore.
It does not show the loading window and not uploading the image.

<a href='https://postimages.org/' target='_blank'><img src='https://s18.postimg.org/yrz1wc85l/Firefox-57-disable-accessbility-services.png' border='0' alt='Firefox-57-disable-accessbility-services'/></a>

**Comment by Inirit** [comment]
I'll look into it, I'll have to learn what parts of the API are being disabled by this option.

**Comment by Inirit** [comment]
Unfortunately I am unable to reproduce this problem. I've checked the box and restarted Firefox, but the extension continues to work just fine.

Can you verify that the extension is installed, enabled, and updated to the latest version?

**Comment by gabri25ele** [comment]
the extension now works without problem, only in that day has not worked.
